const USER_SERVICE_URL = `http://${window.USER_SERVICE_HOSTNAME}:8080`;
const FACILITY_SERVICE_URL = `http://${window.FACILITY_SERVICE_HOSTNAME}:8081`;

export { USER_SERVICE_URL, FACILITY_SERVICE_URL };