version: '3'
services:

  db:
    container_name: postgres
    image: postgres:14.2
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - pgadmin.env
    ports:
      - "5050:80"

volumes:
  postgres:
    name: postgres-volume
