version: '3'
services:
  user-service:
    image: friendcode/capstone_user-service:latest
    ports:
      - 8080:8080
    # RDS
    environment:
      - DB_URL=
      - DB_USERNAME=
      - DB_PASSWORD=
  facility-service:
    image: friendcode/capstone_facility-service:latest
    ports:
      - 8081:8080
    # RDS
    environment:
      - DB_URL=aws.com:5432/endpoint
      - DB_USERNAME=
      - DB_PASSWORD=