# LOCALHOST
@host=http://localhost:8081

# LOAD BALANCER
# @host=

# TOKEN
@jwt=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1c2VyLXNlcnZpY2UiLCJzdWIiOiJtaWNoYWVsYXJuMGxkIiwiaWQiOjEsImF1dGhvcml0aWVzIjoiVVNFUixBRE1JTiIsImV4cCI6MTY0NTY0ODg5OX0.ugGBaaCbFnk-6fMqI9o4EtSGBzy2z0QbxIp6Oz9YRYM

GET {{host}}/helloworld
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1c2VyLXNlcnZpY2UiLCJzdWIiOiJtaWNoYWVsYXJuMGxkIiwiaWQiOjEsImF1dGhvcml0aWVzIjoiVVNFUixBRE1JTiIsImV4cCI6MTY0NTY0ODg5OX0.ugGBaaCbFnk-6fMqI9o4EtSGBzy2z0QbxIp6Oz9YRYM
