# LOCALHOST
@host=http://localhost:8081

# LOAD BALANCER
# @host=http://pete-lb-461189805.us-east-2.elb.amazonaws.com:8081

# TOKEN
@jwt=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1c2VyLXNlcnZpY2UiLCJzdWIiOiJtaWNoYWVsYXJuMGxkIiwiaWQiOjEsImF1dGhvcml0aWVzIjoiVVNFUixBRE1JTiIsImV4cCI6MTY0NjE2OTk5M30.cg4IkpYuunm91l_c5Bxl1jES_DNhm5T1A0sDAlqShZo

###
GET {{host}}/1/1?date=2022-02-22

###
POST {{host}}/2/3
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "appUserId": 2,
    "reservable": {
        "id": 3
    },
    "facility": {
        "id": 2
    },
    "startTime": "2022-02-25T08:00:00",
    "endTime": "2022-02-25T09:00:00"
}

###
GET {{host}}/helloworld/
Authorization: Bearer {{jwt}}