# LOCALHOST
@host=http://localhost:8081

# LOAD BALANCER
# @host=http://pete-lb-461189805.us-east-2.elb.amazonaws.com:8081

# TOKEN
@jwt=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1c2VyLXNlcnZpY2UiLCJzdWIiOiJtaWNoYWVsYXJuMGxkIiwiaWQiOjEsImF1dGhvcml0aWVzIjoiVVNFUixBRE1JTiIsImV4cCI6MTY0NTgwMzk2M30.jMICcHgON2h5zeHHVne9oQL3Oo4QKxhOuYIi-ZLSiZs

GET {{host}}/helloworld
Content-Type: application/json
Authorization: Bearer {{jwt}}
