FROM eclipse-temurin:17-alpine as builder
RUN \
  apk update \
  apk add maven
WORKDIR /home/app
COPY . .
RUN mvn package -Dskiptests -f pom.xml
RUN apk add binutils
RUN $JAVA_HOME/bin/jlink \
    --add-modules java.base,java.compiler,java.desktop,java.instrument,java.logging,java.management,java.naming,java.net.http,java.prefs,java.se,java.security.jgss,java.security.sasl,java.sql,java.sql.rowset,java.transaction.xa,java.xml,java.xml.crypto,jdk.charsets,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.dynalink,jdk.httpserver,jdk.internal.vm.ci,jdk.internal.vm.compiler,jdk.internal.vm.compiler.management,jdk.jdwp.agent,jdk.jfr,jdk.jsobject,jdk.localedata,jdk.management,jdk.management.agent,jdk.management.jfr,jdk.naming.dns,jdk.naming.rmi,jdk.net,jdk.nio.mapmode,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.xml.dom,jdk.zipfs \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=2 \
    --output /jre

FROM alpine:3.14
ENV JAVA_HOME=/opt/java
ENV PATH = "${JAVA_HOME}/bin:${PATH}"
COPY --from=builder /jre ${JAVA_HOME}
EXPOSE 8080/tcp
WORKDIR /home/app
COPY --from=builder /home/app/target/auth-service-0.0.1.jar app.jar
CMD ["java", "-jar", "./app.jar"]