name: CI/CD

on:
  push:
    branches:
      - "main"

env:
  DOCKER_PATH: https://hub.docker.com/repository/docker
  # user
  USER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/capstone-user_service
  # facility
  FACILITY_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/capstone-facility_service
  # ui
  UI_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/capstone-ui

jobs:
  CI-user_service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build & push user-service to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./service/user-service
          push: true
          tags: ${{ env.USER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.USER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.USER_IMAGE_NAME }}:buildcache,mode=max

  CI-facility_service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build & push facility-service to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./service/facility-service
          push: true
          tags: ${{ env.FACILITY_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.FACILITY_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.FACILITY_IMAGE_NAME }}:buildcache,mode=max

  CI-ui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build & push ui image to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          push: true
          tags: ${{ env.UI_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.UI_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.UI_IMAGE_NAME }}:buildcache,mode=max