name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ DOCKER_PASSWORD }}

      - name: Build
        run: |
          docker build -f ui.Dockerfile -t ui .
          docker build -f service.Dockerfile -t service .

      - name: Tag
        run: |
          docker tag ui ${{ secrets.DOCKER_USERNAME }}/ui:${{ github.sha }}
          docker tag ui ${{ secrets.DOCKER_USERNAME }}/ui:latest

          docker tag service ${{ secrets.DOCKER_USERNAME }}/service:${{ github.sha }}
          docker tag service ${{ secrets.DOCKER_USERNAME }}/service:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/ui:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/ui:latest

          docker push ${{ secrets.DOCKER_USER }}/service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/service:latest
