name: CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  ui:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build & push
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/ui:latest

  user-service:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build & push
        uses: docker/build-push-action@v2
        with:
          context: ./user-service
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/user-service:latest