# @host=http://localhost:8080
@host=http://3.131.90.21:8080
@jwt=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1c2VyLXNlcnZpY2UiLCJzdWIiOiJtaWNoYWVsYXJuMGxkIiwiaWQiOjEsImF1dGhvcml0aWVzIjoiVVNFUixBRE1JTiIsImV4cCI6MTY0NTU2MTU1NX0.lFlspnUVlPUmBfS0hLEhyZYkSi1OfcDtWNzUn4EDtlU

###
# GET HOST
GET {{host}} HTTP/1.1

###
# LOGIN AS AN ADMIN
POST {{host}}/login
Content-Type: application/json

{
    "username": "me@michaelarnold.io",
    "password": "P@ssw0rd!"
}

###
# SHOULD TRIGGER EXCEPTION NOT READABLE MESSAGE
POST {{host}}/login
Content-Type: application/json

{
    asdfljasjdfl
    asdfjasldkf;23rkl23J
}

###
# REFRESH TOKEN WITHOUT TOKEN IS 403
POST {{host}}/refresh
Content-Type: application/json

###
# REFRESH TOKEN WITH TOKEN IS 200 OK
POST {{host}}/refresh
Content-Type: application/json
Authorization: Bearer {{jwt}}

###
# CHANGE YOUR PASSWORD
PUT {{host}}/password
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "password": "NEW$$P@ssw0rd!!"
}

###
# REGISTER A NEW USER
POST {{host}}/register
Content-Type: application/json

{
    "membershipId": 1,
    "email": "petey@example.com",
    "username": "petey12345",
    "password": "$$R3gex$$",
    "firstName": "Pete",
    "lastName": "Olson",
    "phone": "888-999-0000",
    "address": "789 Docker Ave",
    "city": "Minneapolis",
    "state": "MN",
    "zipCode": "55372"
}

###
# SIGN IN WITH NEW USER
POST {{host}}/login
Content-Type: application/json

{
    "username": "petey@example.com",
    "password": "$$R3gex$$"
}

###
# CHANGE YOUR PASSWORD
PUT {{host}}/password
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "password": "P@ssw0rd!"
}

###
# YOU MUST SIGN IN AS ADMIN BEFORE THE NEXT TESTS
# GET USERS
GET {{host}}/user
Authorization: Bearer {{jwt}}

###
# GET A SPECIFIC USER
GET {{host}}/user/4
Authorization: Bearer {{jwt}}

###
# UPDATE A SPECIFIC USER
PUT {{host}}/user/update
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "id": 4,
    "membershipId": 1,
    "email": "pete@example.com",
    "username": "petey_whisky",
    "firstName": "Pete",
    "lastName": "Olson",
    "phone": "888-999-0000",
    "address": "789 Docker Ave",
    "city": "Minneapolis",
    "state": "MN",
    "zipCode": "55372",
    "authorities": ["USER"]
}

###
# UPDATE YOURSELF AS AN ADMIN
PUT {{host}}/user/update
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "id": 1,
    "membershipId": 1,
    "email": "me@michaelarnold.io",
    "username": "michaelarnold123",
    "firstName": "Michael",
    "lastName": "Arnold",
    "phone": "888-999-0000",
    "address": "789 Docker Ave",
    "city": "Minneapolis",
    "state": "MN",
    "zipCode": "55372",
    "authorities": ["USER", "ADMIN"]
}

###
# ADMIN CANNOT UPDATE ANOTHER ADMIN; THIS SHOULD RETURN A 403
PUT {{host}}/user/update
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "id": 4,
    "membershipId": 1,
    "email": "pete@example.com",
    "username": "petey_boy",
    "firstName": "Pete",
    "lastName": "Olson",
    "phone": "888-999-0000",
    "address": "789 Docker Ave",
    "city": "Minneapolis",
    "state": "MN",
    "zipCode": "55372",
    "authorities": ["USER"]
}

###
# GET ALL POSSIBLE USER ROLES
GET {{host}}/user/roles
Authorization: Bearer {{jwt}}